name: Node ASAN

on: [push, pull_request]

jobs:
  build-linux-asan-debug:
    runs-on: ubuntu-latest
    container: gengjiawen/node-build
    steps:
      - uses: actions/checkout@v2
      - name: Environment Information
        run: npx envinfo
      - run: git clone https://github.com/nodejs/node --depth=10
      - name: Build
        run: cd node && ./configure --debug --enable-asan --ninja && ninja -C out/Debug
      - name: Test
        run: cd node && python3 tools/test.py -J --mode=debug
        
