name: CI

on: [push, pull_request]

jobs:
  build-linux-debug:
    runs-on: ubuntu-latest
    container: 
     image: gengjiawen/libuv
    name: build-cross-qemu-${{ matrix.config.target }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {target: arm,     toolchain: gcc-arm-linux-gnueabi,     cc: arm-linux-gnueabi-gcc,      qemu: qemu-arm-static     }
    steps:
      - uses: actions/checkout@v2
      - name: Install ${{ matrix.config.toolchain }}
        run: |
          sudo apt install ${{ matrix.config.toolchain }} -y
      - name: Build
        run: |
          git clone https://github.com/libuv/libuv
          cd libuv && mkdir build && cd build
          cmake .. -DBUILD_TESTING=ON -DQEMU=ON -DCMAKE_C_COMPILER=${{ matrix.config.cc }}
          cmake --build .
          ls -lh
          export test_cmd=${matrix.config.qemu} ${GITHUB_WORKSPACE}/libuv/build/uv_run_tests_a
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
      - name: Test
        run: |
          cp libuv/build/uv_run_tests_a /home/user
