name: CI

on: [push, pull_request]

jobs:
  build-linux-lto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Environment Information
        run: npx envinfo
      - run: git clone -b master --single-branch https://github.com/nodejs/node --depth=10
      - name: Build
        run: |
          sudo apt update && sudo apt install ninja-build -y
          cd node
          ./configure --enable-lto --ninja --debug
          ninja -C out/Debug
      - uses: actions/upload-artifact@v2
        with:
          path: node/out/Debug/node
