name: Envinfo Docker Pull

on: [push, pull_request]

jobs:
  envinfo-docker-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Environment Information
        run: npx envinfo
      - name: Pull macOS Tahoe Xcode image
        run: docker pull ghcr.io/cirruslabs/macos-tahoe-xcode:26.5
